#The tags generated by the Tiny Tracer are helpful in deobfuscating obfuscated API calls.
#This script will annotate and bookmark the code with tags produced by tool Tiny Tracer.
#Tiny Tracer repo: https://github.com/hasherezade/tiny_tracer
#@author Jiri_Vinopal
#@category Annotation
#@keybinding 
#@menupath 
#@toolbar 

from ghidra.program.model.listing import CodeUnit
def add_bookmark_comment(addr, apicall):
	cu = currentProgram.getListing().getCodeUnitAt(addr)
	createBookmark(addr, "tiny_tracer", apicall)
	cu.setComment(CodeUnit.EOL_COMMENT, apicall)

f = askFile("Give me a .tag file to import!", "Import")

for line in file(f.absolutePath):
    if line[0] != '>':
    	fields = line.split(";")
    	RVA = fields[0]
    	ApiCall= fields[1].replace('\n', '')
    	addr_int = int(RVA, 16)
    	addr = currentProgram.minAddress.add(addr_int)
    	add_bookmark_comment(addr,ApiCall)
